# Generated by Django 2.2.1 on 2019-05-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjuect_name', models.CharField(max_length=30)),
                ('day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('start_time', models.CharField(choices=[(9, '9시'), (10, '10시'), (11, '11시'), (12, '12시'), (13, '13시'), (14, '14시'), (15, '15시'), (16, '16시'), (17, '17시'), (18, '18시')], max_length=2)),
                ('end_time', models.CharField(choices=[(9, '9시'), (10, '10시'), (11, '11시'), (12, '12시'), (13, '13시'), (14, '14시'), (15, '15시'), (16, '16시'), (17, '17시'), (18, '18시')], max_length=2)),
                ('user_id', models.ForeignKey(on_delete='CASCADE', to='schedule.User')),
            ],
        ),
    ]
