# Generated by Django 2.2.1 on 2019-05-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190505_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='subjuect_name',
            new_name='subject_name',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
