# Generated by Django 2.2.1 on 2019-05-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190505_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('participate', models.ForeignKey(on_delete='CASCADE', to='schedule.User')),
            ],
        ),
    ]
